# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-Plugin-Factory
version:      0.03
version_from: lib/Class/DBI/Plugin/Factory.pm
installdirs:  site
requires:
    Class::DBI:                    0.96
    Class::Inspector:              0
    UNIVERSAL::require:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.29
